databases:
  - name: iconmaker_db
    databaseName: iconmaker_db
    user: iconmaker
    region: singapore

services:
  - type: web
    name: iconmaker
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iconmaker_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
